// Define the FontAwesomeIcons object with all your icons
export const FontAwesomeIcons = {
    attack: 'fa fa-sword',
    defense: 'fa fa-shield-alt',
    move: 'fa fa-walking',
    range: 'fa fa-bullseye',
    // Additional icons for the plugin
    sword: 'fa-solid fa-sword',
    shield: 'fa-solid fa-shield',
    dice: 'fa-solid fa-dice',
    helmet: 'fa-solid fa-helmet',
    bowArrow: 'fa-solid fa-bow-arrow',
    crosshairs: 'fa-solid fa-crosshairs',
    flag: 'fa-solid fa-flag',
    skull: 'fa-solid fa-skull',
    bomb: 'fa-solid fa-bomb',
    cogs: 'fa-solid fa-cogs',
    chess: 'fa-solid fa-chess',
    trophy: 'fa-solid fa-trophy',
    fire: 'fa-solid fa-fire',
    arrowRight: 'fa-solid fa-arrow-right',
    arrowLeft: 'fa-solid fa-arrow-left',
    bolt: 'fa-solid fa-bolt',
    explosion: 'fa-solid fa-explosion',
    truck: 'fa-solid fa-truck',
    wrench: 'fa-solid fa-wrench',
    pistol: 'fa-solid fa-pistol',
    gun: 'fa-solid fa-gun',
    cannon: 'fa-solid fa-cannon',
    car: 'fa-solid fa-car',
    ambulance: 'fa-solid fa-ambulance',
    skiing: 'fa-solid fa-skiing',
    running: 'fa-solid fa-running',
    horse: 'fa-solid fa-horse',
    tank: 'fa-solid fa-tank',
    water: 'fa-solid fa-water',
    ice: 'fa-solid fa-ice',
    cloud: 'fa-solid fa-cloud',
    sun: 'fa-solid fa-sun',
    moon: 'fa-solid fa-moon',
    medkit: 'fa-solid fa-medkit',
    heart: 'fa-solid fa-heart',
    star: 'fa-solid fa-star',
    key: 'fa-solid fa-key',
    rocket: 'fa-solid fa-rocket',
    laptop: 'fa-solid fa-laptop',
    microphone: 'fa-solid fa-microphone',
    phone: 'fa-solid fa-phone',
    layers: 'fa-solid fa-layers',
    radiation: 'fa-solid fa-radiation',
    skullCrossbones: 'fa-solid fa-skull-crossbones',
    clipboardCheck: 'fa-solid fa-clipboard-check',
    clone: 'fa-solid fa-clone',
    fingerprint: 'fa-solid fa-fingerprint',
    balanceScale: 'fa-solid fa-balance-scale',
    shapes: 'fa-solid fa-shapes',
    puzzlePiece: 'fa-solid fa-puzzle-piece',
    bullseye: 'fa-solid fa-bullseye',
    mapMarked: 'fa-solid fa-map-marked',
    locationArrow: 'fa-solid fa-location-arrow',
    certificate: 'fa-solid fa-certificate',
    gift: 'fa-solid fa-gift',
    chartLine: 'fa-solid fa-chart-line',
    users: 'fa-solid fa-users',
    personRunning: 'fa-solid fa-person-running',
    userShield: 'fa-solid fa-user-shield',
    streetView: 'fa-solid fa-street-view',
    mountain: 'fa-solid fa-mountain',
    trees: 'fa-solid fa-trees',
    campground: 'fa-solid fa-campground',
    bicycle: 'fa-solid fa-bicycle',
    walking: 'fa-solid fa-walking',
    plane: 'fa-solid fa-plane',
    helicopter: 'fa-solid fa-helicopter',
    fighterJet: 'fa-solid fa-fighter-jet',
    submarine: 'fa-solid fa-submarine',
    ship: 'fa-solid fa-ship'
};

// Function to get the FontAwesome icon class for a specific action type
export function getFontAwesomeIcon(type: string): string {
    return FontAwesomeIcons[type] || 'fa fa-question'; // Default to question mark if no icon found
}
